package com.sungolden.rsai.dao;

import com.sungolden.rsai.dto.Data;

public interface DataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    int insert(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    int insertSelective(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    Data selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    int updateByPrimaryKeySelective(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    int updateByPrimaryKey(Data record);
}