package com.sungolden.rsai.dto;

import java.io.Serializable;
import java.util.Date;

public class Data implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.id
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.source_id
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    private Integer sourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.date
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.id
     *
     * @return the value of data.id
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.id
     *
     * @param id the value for data.id
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.source_id
     *
     * @return the value of data.source_id
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.source_id
     *
     * @param sourceId the value for data.source_id
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.date
     *
     * @return the value of data.date
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.date
     *
     * @param date the value for data.date
     *
     * @mbg.generated Thu May 14 15:54:59 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }
}